<?php

class Zend_View_Helper_AuthUrl extends Zend_View_Helper_Url
{
    public function authUrl(array $urlOptions = array(), $name = null, $reset = false, $encode = true)
    {
        return parent::url($urlOptions, $name, $reset, $encode); // TODO: Change the autogenerated stub
    }
}