<?php

class Auth_AuthController extends Zend_Controller_Action
{

    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub

    }

    /**
     *
     *
     * check user authentications
     *
     */
    public function indexAction()
    {
        if (Zend_Auth::getInstance()->hasIdentity()) {
            return $this->redirect('auth/profile');
        }

        $request = $this->_request;
        if ($request->isPost()) {
            $data = $request->getPost();
            $db = $this->_getParam('db');
            $adapter = new Zend_Auth_Adapter_DbTable(
                $db,
                'users',
                'email',
                'password',
                'MD5(?)'
            );
            $adapter->setIdentity($data['email']);
            $adapter->setCredential($data['password']);

            $auth = Zend_Auth::getInstance();
            $result = $auth->authenticate($adapter);
            if ($result->isValid()) {
                $this->_helper->success = 'Successful Login';
                return $this->redirect('auth/profile');
            }
        }

    }


    /**
     *
     * logout
     *
     */
    public function logoutAction()
    {
        $auth = Zend_Auth::getInstance();
        if (!$auth->hasIdentity()) {
            return $this->redirect('auth/login');
        }
        $auth->clearIdentity();
        return $this->redirect('auth/login');

    }
}