<!--PAGE CONTENT START-->
<div class="row">
    <div class="col-md-12">
        <form action="" id="contact-us" method="POST">
            <div class="form-group">
                <label for="name">User name</label>
                <input type="text" class="form-control" name="name">
            </div>

            <div class="form-group">
                <label for="email">Email</label>
                <input type="text" class="form-control" name="email">
            </div>

            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" class="form-control" name="title">
            </div>
            <div class="form-group">
                <label for="message">Message</label>
                <textarea name="message" id="" cols="30" rows="6" class="form-control"></textarea>
            </div>
            <div class="form-action text-center">
                <input type="submit" name="submit" value="Submit" class="btn btn-primary">
                <input type="reset" name="reset" value="Cancel" class="btn btn-danger">
            </div>

        </form>
    </div>
</div>
<!--PAGE CONTENT END-->
<!--PAGE LEVEL SCRIPT START-->
<?php //$this->headScript()->appendFile('js/create.js', 'text/javascript'); ?>
<!--PAGE LEVEL SCRIPT END-->


