<?php


class Lang_LangController extends Zend_Controller_Action
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->_helper->layout()->disableLayout();
        $this->_helper->viewRenderer->setNoRender(true);

        $context = $this->getHelper('ContextSwitch');
        $context->addActionContext(['index'], 'json')
            ->initContext();
        $this->getResponse()->setHeader('Content-Type', 'application/json');

    }

    public function indexAction()
    {
        $request = $this->getRequest();
        $response = $this->getResponse();
        $langSession = new Zend_Session_Namespace('demo');
        $langSession->lang = $request->getParam('lang');
        return $this->redirect($_SERVER['HTTP_REFERER']);

    }
}